Auto bump workflow

diff --git a/.github/workflows/release_to_pypi.yml b/.github/workflows/release_to_pypi.yml
--- a/.github/workflows/release_to_pypi.yml
+++ b/.github/workflows/release_to_pypi.yml
@@ -1,9 +1,8 @@
-name: Publish to PyPI & GitHub
+name: Publish to PyPI
 
 on:
-  push:
-    tags:
-      - "v*"
+  release:
+    types: [created]
 
 jobs:
   build-and-publish:
@@ -18,6 +17,23 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: "3.x"
+
+      - name: Autobump version
+        shell: bash
+        run: |
+          # from refs/tags/v1.2.3 get 1.2.3
+          VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
+          PER_LENGTH=$(tr -dc ',' <<< "$VERSION" | awk '{ print length; }')
+          if [ "$PER_LENGTH" = "3" ]; then
+            echo "$VERSION does not contain major/minor/patch/!"
+            exit 1
+          fi
+          PLACEHOLDER='__version__ = "develop"'
+          VERSION_FILE='BrowserWrapper/__init__.py'
+          # ensure the placeholder is there. If grep doesn't find the placeholder
+          # it exits with exit code 1 and github actions aborts the build.
+          grep "$PLACEHOLDER" "$VERSION_FILE"
+          sed -i "s/$PLACEHOLDER/__version__ = \"${VERSION}\"/g" "$VERSION_FILE"
 
       - name: Build source and wheel distributions
         run: |
